version: '3'

services:
  # MySQL service
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - ban2-network

  # Java application service
  java-app:
    build:
      context: ./SchoolManagerAPI
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - ban2-network

    # Angular service
  angular-app:
      build:
        context: ./SchoolManagerAngularClient
        dockerfile: Dockerfile
      ports:
        - "4200:4200"
      networks:
        - ban2-network
      depends_on:
        - java-app

networks:
  ban2-network:
    driver: bridge
